[dune_queries.dex_volume]
query = "https://dune.com/queries/4388"
primary_key = ["project", "_col1"]
replication_key = "_col1"
write_disposition = "merge"

##### example with query params #####
[dune_queries.y2k_price_data]
query = 4749625 # just the query id also works. Query URL: https://dune.com/queries/4749625
primary_key = ["timestamp", "blockchain", "contract_address"] # multi PK example
write_disposition = "merge"
query_params = '{"symbol": "Y2K"}'

##### same as above but no primary key #####
[dune_queries.y2k_price_data_no_pk]
query = 4749625
write_disposition = "merge" # will be overriden by "append" if no primary key is set
query_params = '{"symbol": "Y2K"}'

##### example with custom SQL #####
[dune_queries.custom_sql]
query = """
SELECT 
    timestamp,
    blockchain,
    contract_address,
    symbol,
    price
FROM prices.day 
WHERE symbol = 'BRETT' 
AND blockchain = 'base'
AND contract_address = from_hex('532f27101965dd16442e59d40670faf5ebb142e4')
order by timestamp
"""
primary_key = "timestamp"
replication_key = "timestamp"
write_disposition = "merge"